model_name_or_path: weights/document_info/merged
trust_remote_code: true
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target: all
freeze_vision_tower: false
freeze_multi_modal_projector: false
dataset_dir: database/score_support/info_crop_rehearsal
dataset: info_train
eval_dataset: info_validation
template: glm_ocr
cutoff_len: 6144
preprocessing_num_workers: 16
overwrite_cache: true
output_dir: output/document_info
logging_steps: 20
save_steps: 700
eval_steps: 700
eval_strategy: steps
save_total_limit: 3
plot_loss: true
overwrite_output_dir: false
report_to: none
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
gradient_accumulation_steps: 4
train_sampling_strategy: group_by_length
learning_rate: 1.0e-05
num_train_epochs: 1.5
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
gradient_checkpointing: true
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
dataloader_num_workers: 4
ddp_timeout: 18000
seed: 20260929
data_seed: 20260929
flash_attn: fa2
tokenized_path: database/score_support/info_crop_rehearsal/balanced
early_stopping_steps: 4
disable_gradient_checkpointing: false
image_max_pixels: 2016000
